import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, MapPin, Phone, Calendar, AlertTriangle, CheckCircle, Clock } from 'lucide-react';

interface DiagnosticReportProps {
  diagnosis: {
    symptoms: string;
    assessment: string;
    timestamp: Date;
  };
  onFindHospitals?: () => void;
}

export const DiagnosticReport = ({ diagnosis, onFindHospitals }: DiagnosticReportProps) => {
  const getSeverityLevel = (assessment: string) => {
    if (assessment.includes('immediate') || assessment.includes('emergency') || assessment.includes('serious')) {
      return { level: 'high', color: 'destructive', icon: AlertTriangle };
    } else if (assessment.includes('medical attention') || assessment.includes('healthcare provider')) {
      return { level: 'medium', color: 'warning', icon: Clock };
    } else {
      return { level: 'low', color: 'success', icon: CheckCircle };
    }
  };

  const severity = getSeverityLevel(diagnosis.assessment);
  const SeverityIcon = severity.icon;

  const generateReportId = () => {
    return `RHL-${Date.now().toString().slice(-6)}`;
  };

  const downloadReport = () => {
    const reportContent = `
RURAL HEALTH LINK - DIAGNOSTIC REPORT
=====================================

Report ID: ${generateReportId()}
Date: ${diagnosis.timestamp.toLocaleDateString()}
Time: ${diagnosis.timestamp.toLocaleTimeString()}

PATIENT SYMPTOMS:
${diagnosis.symptoms}

AI ASSESSMENT:
${diagnosis.assessment}

SEVERITY LEVEL: ${severity.level.toUpperCase()}

RECOMMENDATIONS:
${severity.level === 'high' 
  ? '• Seek immediate medical attention\n• Visit nearest emergency department\n• Call emergency services if symptoms worsen'
  : severity.level === 'medium'
  ? '• Schedule appointment with healthcare provider within 24 hours\n• Monitor symptoms closely\n• Contact doctor if symptoms worsen'
  : '• Rest and monitor symptoms\n• Stay hydrated\n• Consult healthcare provider if symptoms persist beyond 3 days'
}

DISCLAIMER:
This assessment is for informational purposes only and should not replace professional medical advice. Always consult with a qualified healthcare provider for proper diagnosis and treatment.

Generated by Rural Health Link AI Assistant
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `health-report-${generateReportId()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card className="border-l-4 border-l-medical-blue shadow-lg">
        <CardHeader className="bg-gradient-to-r from-medical-light to-accent/50">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileText className="w-6 h-6 text-medical-blue" />
              <CardTitle className="text-medical-blue">Diagnostic Report</CardTitle>
            </div>
            <Badge variant={severity.color as any} className="flex items-center gap-1">
              <SeverityIcon className="w-3 h-3" />
              {severity.level.toUpperCase()} PRIORITY
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-4 p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <h4 className="font-semibold text-sm text-muted-foreground uppercase tracking-wide">Report Details</h4>
              <div className="space-y-1">
                <div className="flex items-center gap-2 text-sm">
                  <Calendar className="w-4 h-4 text-medical-blue" />
                  <span>{diagnosis.timestamp.toLocaleDateString()} at {diagnosis.timestamp.toLocaleTimeString()}</span>
                </div>
                <div className="flex items-center gap-2 text-sm">
                  <FileText className="w-4 h-4 text-medical-blue" />
                  <span>Report ID: {generateReportId()}</span>
                </div>
              </div>
            </div>
            <div className="space-y-2">
              <h4 className="font-semibold text-sm text-muted-foreground uppercase tracking-wide">Assessment Status</h4>
              <div className={`p-3 rounded-lg border-l-4 ${
                severity.level === 'high' ? 'bg-destructive/10 border-l-destructive' :
                severity.level === 'medium' ? 'bg-yellow-50 border-l-yellow-500' :
                'bg-green-50 border-l-green-500'
              }`}>
                <div className="flex items-center gap-2">
                  <SeverityIcon className={`w-4 h-4 ${
                    severity.level === 'high' ? 'text-destructive' :
                    severity.level === 'medium' ? 'text-yellow-600' :
                    'text-green-600'
                  }`} />
                  <span className="font-medium text-sm">
                    {severity.level === 'high' ? 'Urgent Medical Attention Required' :
                     severity.level === 'medium' ? 'Medical Consultation Recommended' :
                     'Monitor and Rest'}
                  </span>
                </div>
              </div>
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="font-semibold text-sm text-muted-foreground uppercase tracking-wide">Reported Symptoms</h4>
            <Card className="p-4 bg-muted/50">
              <p className="text-sm">{diagnosis.symptoms}</p>
            </Card>
          </div>

          <div className="space-y-3">
            <h4 className="font-semibold text-sm text-muted-foreground uppercase tracking-wide">AI Assessment</h4>
            <Card className="p-4 bg-gradient-to-r from-medical-light to-accent/20 border-medical-blue/20">
              <p className="text-sm leading-relaxed">{diagnosis.assessment}</p>
            </Card>
          </div>

          <div className="space-y-3">
            <h4 className="font-semibold text-sm text-muted-foreground uppercase tracking-wide">Recommendations</h4>
            <div className="grid gap-3">
              {severity.level === 'high' && (
                <div className="space-y-2">
                  <div className="flex items-center gap-2 p-3 bg-destructive/10 rounded-lg border border-destructive/20">
                    <AlertTriangle className="w-4 h-4 text-destructive" />
                    <span className="text-sm font-medium">Seek immediate medical attention</span>
                  </div>
                  <div className="flex items-center gap-2 p-3 bg-muted/50 rounded-lg">
                    <Phone className="w-4 h-4 text-medical-blue" />
                    <span className="text-sm">Call emergency services if symptoms worsen</span>
                  </div>
                </div>
              )}
              {severity.level === 'medium' && (
                <div className="space-y-2">
                  <div className="flex items-center gap-2 p-3 bg-yellow-50 rounded-lg border border-yellow-200">
                    <Clock className="w-4 h-4 text-yellow-600" />
                    <span className="text-sm font-medium">Schedule appointment within 24 hours</span>
                  </div>
                  <div className="flex items-center gap-2 p-3 bg-muted/50 rounded-lg">
                    <CheckCircle className="w-4 h-4 text-medical-green" />
                    <span className="text-sm">Monitor symptoms closely</span>
                  </div>
                </div>
              )}
              {severity.level === 'low' && (
                <div className="space-y-2">
                  <div className="flex items-center gap-2 p-3 bg-green-50 rounded-lg border border-green-200">
                    <CheckCircle className="w-4 h-4 text-green-600" />
                    <span className="text-sm font-medium">Rest and monitor symptoms</span>
                  </div>
                  <div className="flex items-center gap-2 p-3 bg-muted/50 rounded-lg">
                    <Clock className="w-4 h-4 text-medical-blue" />
                    <span className="text-sm">Consult healthcare provider if symptoms persist beyond 3 days</span>
                  </div>
                </div>
              )}
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t">
            <Button onClick={downloadReport} variant="outline" className="flex-1">
              <Download className="w-4 h-4 mr-2" />
              Download Report
            </Button>
            <Button onClick={onFindHospitals} variant="medical" className="flex-1">
              <MapPin className="w-4 h-4 mr-2" />
              Find Nearby Hospitals
            </Button>
          </div>
        </CardContent>
      </Card>

      <Card className="bg-gradient-to-r from-yellow-50 to-orange-50 border-yellow-200">
        <CardContent className="p-4">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-yellow-600 mt-0.5" />
            <div className="space-y-1">
              <h4 className="font-semibold text-yellow-800">Important Disclaimer</h4>
              <p className="text-sm text-yellow-700">
                This AI assessment is for informational purposes only and should not replace professional medical advice. 
                Always consult with a qualified healthcare provider for proper diagnosis and treatment.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};